[package]
authors = ["Alexandre Bury <alexandre.bury@gmail.com>"]
name = "coinched"
version = "0.0.1"

[dependencies]
bodyparser = "0.0.6"
eventual = "0.1.5"
iron = "0.2.6"
rand = "0.3.12"
rustc-serialize = "0.3.16"
time = "0.1.34"
