[package]
authors = ["Alexandre Bury <alexandre.bury@gmail.com>"]
name = "coinched"
version = "0.0.1"

[dependencies]
bodyparser = "0.0.6"
iron = "0.2.6"
rand = "0.3.12"
rustc-serialize = "0.3.16"
time = "0.1.34"
# Crates.io currently uses an outdated version
# eventual = "0.1.4"

[dependencies.eventual]
git = "https://github.com/carllerche/eventual"
