[package]
name = "coinched"
version = "0.0.1"
authors = ["Alexandre Bury <alexandre.bury@gmail.com>"]

[dependencies]
rand = "0.3.7"
time = "*"

[dependencies.iron]
verion = "*"

[dependencies.bodyparser]
git = "https://github.com/iron/body-parser.git"
