[package]
authors = ["Alexandre Bury <alexandre.bury@gmail.com>"]
name = "coinched"
version = "0.0.1"
license = "MIT"
repository = "https://github.com/Gyscos/coinched"
description = "A coinche server"

[dependencies]
bodyparser = "0.0.6"
eventual = "0.1.5"
iron = "0.2.6"
libcoinche = "0.1.5"
rand = "0.3.12"
rustc-serialize = "0.3.16"
time = "0.1.34"

[[bin]]
name = "coinched"
doc = false
